---
- name: Déployer une app Node.js avec Docker + Nginx + Reverse Proxy multi-ports
  hosts: all
  become: yes

  vars_prompt:
    - name: "repo_url"
      prompt: "URL du dépôt Git"
      private: no
    - name: "container_name"
      prompt: "Nom du conteneur"
      private: no
    - name: "docker_image_name"
      prompt: "Nom de l'image Docker"
      private: no
    - name: "app_type"
      prompt: "Type d'application (react, vue, nestjs, express, nextjs,svelte, angular,nuxt,next)"
      private: no
    - name: "node_version"
      prompt: "Version de Node.js (ex: 18-alpine)"
      private: no

  tasks:
    - name: Définir le dossier de build
      set_fact:
        build_dir: "/opt/{{ container_name }}_build"

    - name: Enregistrer l'heure de début (epoch)
      shell: date +%s
      register: start_time_cmd

    - name: Installer Docker et Nginx
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io
        - nginx

    - name: Créer le dossier de build
      file:
        path: "{{ build_dir }}"
        state: directory
        mode: "0755"

    - name: Sélectionner le template Dockerfile
      set_fact:
        dockerfile_template: "Dockerfile.{{ app_type | lower }}.j2"

    - name: Générer le Dockerfile avec template
      template:
        src: "templates/{{ dockerfile_template }}"
        dest: "{{ build_dir }}/Dockerfile"

    - name: Supprimer conteneur et image Docker existants
      block:
        - name: Supprimer conteneur Docker
          community.docker.docker_container:
            name: "{{ container_name }}"
            state: absent
            force_kill: true
          ignore_errors: true

        - name: Supprimer image Docker
          community.docker.docker_image:
            name: "{{ docker_image_name }}"
            state: absent
            force_absent: true
          ignore_errors: true

    - name: Construire l’image Docker
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        build:
          path: "{{ build_dir }}"
          nocache: true
          pull: true
        source: build

    - name: Supprimer les images <none> inutiles
      shell: docker images -f "dangling=true" -q | xargs -r docker rmi
      args:
        executable: /bin/bash

    - name: Trouver un port libre à partir de 801
      vars:
        start_port: 801
        max_port: 8100
      block:
        - name: Générer liste de ports candidats
          set_fact:
            candidate_ports: "{{ range(start_port, max_port) | list }}"

        - name: Choisir le premier port libre
          shell: |
            for port in {{ candidate_ports | join(' ') }}; do
              ss -tuln | grep ":$port " > /dev/null || { echo $port; break; }
            done
          register: chosen_port
          changed_when: false

        - name: Enregistrer le port libre
          set_fact:
            exposed_port: "{{ chosen_port.stdout | int }}"

    - name: Démarrer le conteneur
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ exposed_port }}:{% if app_type in ['react', 'vue', 'angular', 'svelte'] %}80{% else %}3000{% endif %}"
        env:
          NODE_ENV: production

    - name: Configurer le reverse proxy Nginx
      block:
        - name: Créer config proxy Nginx
          copy:
            dest: "/etc/nginx/sites-available/{{ container_name }}_proxy.conf"
            content: |
              server {
                  listen {{ exposed_port }};
                  server_name _;

                  location / {
                      proxy_pass http://localhost:{{ exposed_port }};
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_set_header Host $host;
                      proxy_cache_bypass $http_upgrade;
                  }
              }

        - name: Activer la config proxy
          file:
            src: "/etc/nginx/sites-available/{{ container_name }}_proxy.conf"
            dest: "/etc/nginx/sites-enabled/{{ container_name }}_proxy.conf"
            state: link
            force: yes

    - name: Recharger Nginx
      service:
        name: nginx
        state: reloaded

    - name: Obtenir IP locale
      shell: hostname -I | awk '{print $1}'
      register: local_ip

    - name: Obtenir IP publique
      command: curl -s http://checkip.amazonaws.com
      register: public_ip

    - name: Enregistrer l'heure de fin (epoch)
      shell: date +%s
      register: end_time_cmd

    - name: Vérifier que les timestamps sont définis
      fail:
        msg: "Timestamp start_time_cmd.stdout ou end_time_cmd.stdout manquant"
      when: start_time_cmd.stdout is not defined or end_time_cmd.stdout is not defined

    - name: Calculer durée (min:sec)
      set_fact:
        duration_seconds: "{{ end_time_cmd.stdout | int - start_time_cmd.stdout | int }}"
        duration_minutes: "{{ (end_time_cmd.stdout | int - start_time_cmd.stdout | int) // 60 }}"
        duration_remaining_seconds: "{{ (end_time_cmd.stdout | int - start_time_cmd.stdout | int) % 60 }}"

    - name: Afficher résultat final
      debug:
        msg: |
          ✅ Application déployée avec succès !
          🕓 Temps total : {{ duration_minutes }} min {{ duration_remaining_seconds }} s
          🌐 Accès local  : http://{{ local_ip.stdout | trim }}:{{ exposed_port }}
          🌍 Accès public : http://{{ public_ip.stdout | trim }}:{{ exposed_port }}
