---
- hosts: all
  become: true
  tasks:
    - name: Remove nginx if installed
      apt:
        name: nginx
        state: absent
    - name: Install Apache package
      apt:
        name: apache2
    #     state: present

    # - name: Ensure Apache is running
    #   service:
    #     name: apache2
    #     state: started
    #     enabled: true

    # - name: Create a simple HTML file
    #   copy:
    #     content: "<h1>Hello, Ansible!</h1>"
    #     dest: /var/www/html/index.html
