FROM node:{{ node_version| default("20-alpine")}}
WORKDIR /app
RUN apk add --no-cache git
RUN git clone --depth=1 {{ repo_url }} .
RUN yarn install
RUN yarn build
EXPOSE 3000
CMD ["node", "dist/main.js"]
