FROM node:{{ node_version }} as builder

WORKDIR /app

# Installer Git et cloner le dépôt
RUN apk add --no-cache git
RUN git clone --depth=1 {{ repo_url }} .

# Installer les dépendances et build l'app
RUN yarn install
RUN yarn build
RUN yarn export

# Étape de déploiement avec Nginx
FROM nginx:alpine

# Copier les fichiers exportés vers nginx
COPY --from=builder /app/out /usr/share/nginx/html

# Supprimer la config Nginx par défaut et ajouter la tienne
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
