FROM node:{{ node_version | default("20-alpine")}} as builder
WORKDIR /app
RUN apk add --no-cache git
RUN git clone --depth=1 {{ repo_url }} .
RUN yarn install
RUN yarn build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
