FROM node:{{ node_version }} as builder

WORKDIR /app

# Installer Git et cloner le dépôt
RUN apk add --no-cache git
RUN git clone --depth=1 {{ repo_url }} .

# Installer les dépendances
RUN yarn install

# Générer l'app statique
RUN yarn generate

# Étape de déploiement avec Nginx
FROM nginx:alpine

# Copier les fichiers générés vers nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Supprimer la config par défaut de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Ajouter une config Nginx optimisée pour les apps SPA/Nuxt
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
