FROM node:{{ node_version }} as builder
WORKDIR /app
RUN apk add --no-cache git
RUN git clone --depth=1 {{ repo_url }} .
RUN yarn install
RUN yarn global add @angular/cli
RUN ng build --configuration production --output-path=dist/{{ docker_image_name }}

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/{{ docker_image_name }}/browser/. /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
